import React from "react";

export const userSampleImage =
    "https://www.pinclipart.com/picdir/big/165-1653686_female-user-icon-png-download-user-colorful-icon.png";

export const themeConfig = {
    heading: {
        poppinsHeading: "Poppins",
        poppinsHeadingSize: "32px",
        latoHeading: "Lato",
        latoHeadingSize: "32px",
    },
    paragraph: {
        poppinsPara: "Poppins",
        poppinsParaSize: "18px",
        poppinsParaSize2: "16px",
        latoPara: "Lato",
        latoParaSize: "18px",
        latoParaSize2: "16px",
    },
    backgroundColor: "#309b42",
    backgroundColorSecondary: "#e4e7eb",
    darkGrey: "#1f2933",
    grey: "#4d5966",
    lightGrey: "#9aa5b1",
    lightenGrey: "#e4e7eb",
    bgGrey: "#f5f7fa",
};

export const allTranslations = {
    buttons: {
        next: "Next",
        save: "Save",
        signIn: "Sign In",
        addRole: "Add Role",
        addUser: "Add User",
        letMeIn: "Let Me In",
        editUser: "Edit User",
        editRole: "Edit Role",
        inviteUser: "Invite User",
        updateUser: "Update User",
        updateRole: "Update Role",
        verifyCode: "Verify Code",
        letsExplore: "Lets Explore",
        editFirmware: "Edit Firmware",
        updateProfile: "Update Profile",
        resetPassword: "Reset Password",
        createPassword: "Create Password",
        forgotPassword: "Forgot Password",
    },
    tables: {
        ip: "IP",
        imsi: "IMSI",
        date: "Date",
        role: "Role",
        name: "Name",
        iccid: "ICCID",
        users: "Users",
        phone: "Phone",
        error: "Error",
        serial: "Serial",
        status: "Status",
        gender: "Gender",
        office: "Office",
        region: "Region",
        failed: "Failed",
        action: "Actions",
        partner: "Partner",
        request: "Request",
        country: "Country",
        actions: "Actions",
        version: "Version",
        endDate: "End Date",
        progress: "Progress",
        progress: "Progress",
        fileName: "File Name",
        fullName: "Full Name",
        analytics: "Analytics",
        hubSerial: "Hub Serial",
        createdAt: "Created At",
        occurences: "Occurences",
        deviceType: "Device type",
        description: "Description",
        errorDetail: "Error Detail",
        updatedDate: "Updated Date",
        createdDate: "Created Date",
        dateAndTime: "Date and Time",
        connectivity: "Connectivity",
        customerName: "Customer Name",
        deviceStatus: "Device Status",
        systemStatus: "System Status",
        activeDevices: "Active Devices",
        authorityLevel: "Authority Level",
        lastConnectivity: "Last Connectivity",
        disconnectedSince: "Disconnected Since",
    },
    email: "Email",
    password: "Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    designation: "Designation",
    confirmPassword: "Confirm Password",
    rememberMe: "Remember Me",
    signIn: "Sign In",
    verificationCode: "Verification Code",
    verifyCode: "Verify Code",
    passwordRecovery: "Password Recovery",
    SignInInfo: "Sign in to access your account!",
    setupAccount: "Setup Your Account",
    connectedHubs: "Connected Hubs",
    disconnectedHubs: "Disconnected Hubs",
    energyProduction: "Energy Production",
    alarms: "Alarms",
    energyStatistic: "Energy Statistics",
    tickets: "Tickets",
    production: "Production",
    consumption: "Consumption",
    viewAll: "View All",
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    goodNight: "Good Night",
    basicInfo: "Basic Info",
    securityInfo: "Security Info",
    setupAccountInfo:
        "Start with you company email and create your password on next step",
    createPassword: "Create Your Password",
    createPasswordInfo: "Please set your password to complete your account!",
    createSuccessfully: "Your account has been successfully registered.",
    resetSuccessfully: "Your password has been reset successfully.",
    createdSuccessfullyInfo: "Welcome to our X-Solar family.",
    resetSuccessfullyInfo: "You can now login.",
    forgotPasswordVerification: "",
    forgotPasswordInitialText:
        "Don’t worry. Resetting your password is easy, just tell us the email address you registered with us.",
    forgotPasswordFinalText1: "We sent a reset password email to",
    forgotPasswordFinalText2:
        "Please click the reset password link to set your new password or enter the received code.",
    resetPasswordText: "Please enter your new password.",
    emailNotReceived: "Didn't receive the email yet?",
    checkAgain: "Please check your spam folder, or",
    tryAgain: "try again",
    addRoleFirst: "Start by adding first role",
    addUserFirst: "Start by adding first user",
    addUserFirstDesc:
        "Add a user to build up your flow by clicking the button on top right corner. That will help your team to use the support portal.",
    addRoleFirstDesc:
        "Add a role to build up your flow by clicking the button on top right corner. That will help you to assign the permissions to the users.",
    globalSearchPlaceholder: "Hub serial number, customer mobile number or name",
};

export const errorMessages = {
    networkError: "Network Error",
    emailEmpty: "Email cannot be empty",
    sessionExpired: "Session Expired!",
    userAlreadyExists: "User with entered email already exists!",
    roleAlreadyExists: "Role with entered name already exists!",
    anErrorHasOccurred: "An Error Has Occurred!",
    somethingWentWrong: "Something Went Wrong",
    tokenExpired: "The invite link has expired!",
    passwordMismatch: "Passwords does not match!",
    currentNewPassword: "Current and New Passwords cannot be the same",
    invalidEmail: "Please enter a valid email address",
    emailPasswordError: "Please enter Email and Password",
    emailMismatch: "Email does not match the email in invite",
    invalidVerificationCode: "Invalid Verification Code",
    invalidPassword:
        "Your password must be at least 6 characters long (safety first)",
    domainEmail:
        'Please enter your "xsolar" email id you can’t setup an account with other email',
    accountSuspended:
        "Your account is suspended for some resons please contact with admin support.",
};